### ISSUE TITLE
Overrides fail on local modpack

### ISSUE THREAD

**Issue by MrNavaStar** [nothub/mrpack-install#40] opened 2024-03-04 00:32 UTC
I have a modpack that my friend made, and when I try to create a server  using this tool the overrides fail to extract. 

Running this command:
![Screenshot from 2024-03-03 17-28-13](https://github.com/nothub/mrpack-install/assets/43613843/1d886903-b9f6-4bf5-93ea-79d025ca3868)
Results in this:
![Screenshot from 2024-03-03 17-28-32](https://github.com/nothub/mrpack-install/assets/43613843/de397cbc-1d19-41c6-a1d5-686811ac3775)

Not a huge issue as the overrides can be extracted manually, but would be awesome if It can be addressed. 
Cheers! Awesome tool btw!

**Comment by nothub** [comment] 2024-03-05 08:59
Hey @MrNavaStar , thanks for your report!

Can you provide an example mrpack file for me to test?

**Comment by MrNavaStar** [comment] 2024-03-05 19:29
Sure thing! This is the one I used. I Just renamed the file from mrpack to zip so It would let me upload it 

[Wings_Of_Adventure_1.0.0.zip](https://github.com/nothub/mrpack-install/files/14500317/Wings_Of_Adventure_1.0.0.zip)

**Comment by nothub** [comment] 2024-03-08 08:47
I just tested and can confirm your issue.
The issue happens in the `v0.17.0-indev` pre-release.
The current stable release `v0.16.10` seems to be fine.

Please use the current stable release for now. The issue will be fixed in a future release.

I will keep the Ticket open to track this bug.

**Comment by MrNavaStar** [comment] 2024-03-09 22:45
Oh I didn't realize I was on a beta build. Thanks!

**Comment by nothub** [comment] 2024-04-02 22:40
I just published a new pre-release version [v0.17.0-beta](https://github.com/nothub/mrpack-install/releases/tag/v0.17.0-beta).
With that version I can now successfully install the mrpack file you provided.

@MrNavaStar can you verify that the issue is also solved for you when using the new version?

**Comment by nothub** [comment] 2024-04-06 16:05
I tested again on linux amd64 and the issue is fixed. If you experience another issue related to this ticket, just reopen it.

**Closed by nothub** 2024-04-06 16:05 UTC
